name: LINUX BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make install
      
    - name: Run check
      run: make test
      
