name: LINUX BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make install
      
    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.1
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.73.0
          # OPTIONAL: Specify a platform version
          platform_version: 18.04
          # OPTIONAL: Specify a custom install location
          boost_install_dir: /home/runner/some_directory
          # OPTIONAL: Specify a toolset
          toolset: gcc
          # OPTIONAL: Specify an architecture
          arch: x86

          # NOTE: If a boost version matching all requirements cannot be found,
          # this build step will fail
      
    - name: Run check
      run: make test
      
