name: WINDOWS BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  #TEST UNDER WINDOWS
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Windows)
      run: make install
      shell: bash  # optional: if you want to run bash commands on Windows runners
      
    - name: Run tests (Windows)
      run: make test
      shell: bash  # or cmd / powershell depending on your makefile and environment
